### ISSUE TITLE
ParaView pyMINFLUX reader plug-in incompatible with ParaView 5.12

### ISSUE THREAD

**Issue by aarpon** [bsse-scf/pyMINFLUX#14]
**Describe the bug**
When opening `.pmx` files in ParaView 5.12, the plug-in fails with the following error message:

```
ERROR: In vtkPythonAlgorithm.cxx, line 97
vtkPythonAlgorithm (0xbd2630): Failure when calling method: "ProcessRequest":

Traceback (most recent call last):
  File "ParaView-5.12.0-MPI-Linux-Python3.10-x86_64/lib/python3.10/site-packages/vtkmodules/util/vtkAlgorithm.py", line 152, in ProcessRequest
    return vtkself.ProcessRequest(request, inInfo, outInfo)
  File "ParaView-5.12.0-MPI-Linux-Python3.10-x86_64/lib/python3.10/site-packages/vtkmodules/util/vtkAlgorithm.py", line 198, in ProcessRequest
    return self.RequestData(request, inInfo, outInfo)
  File "pyMINFLUX/paraview_plugins/pyminflux_reader.py", line 67, in RequestData
    layout, render_view = self.create_new_layout()
  File "pyMINFLUX/paraview_plugins/pyminflux_reader.py", line 179, in create_new_layout
    render_view = CreateView("RenderView", "Localizations")
TypeError: CreateView() takes 1 positional argument but 2 were given
ERROR: In vtkExecutive.cxx, line 729
vtkPVCompositeDataPipeline (0x5954250): Algorithm vtkPythonAlgorithm (0xbd2630) returned failure for request: vtkInformation (0x5a6fc60)
  Debug: Off
  Modified Time: 574855
  Reference Count: 2
  Registered Events: (none)
  Request: REQUEST_DATA
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0
```

**To Reproduce**
Install the `pyminflux_reader.py` plug-in in ParaView and open a `.pmx` file.

**Expected behavior**
The plug-in should work correctly as in ParaView version 5.11.

**Environment (please complete the following information):**
 - OS: all supported OSes
 - PyMINFLUX Version: 0.4.0

**Comment by aarpon** [comment]
In ParaView 5.11, `paraview.simple.CreateView()` could take a second, optional argument, that is removed in ParaView 5.12. Removing it seems to fix the issue. Testing.

**Comment by aarpon** [comment]
Closed by pull request.
